language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run coverage
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
